version: '3'
services:
  uptime-kuma:
    container_name: 'uptime-robot'
    image: louislam/uptime-kuma:latest
    restart: always
    volumes:
      - /mnt/uptimekuma:/app/data
    ports:
      - 3001:3001
